exclude:
  - '**/*.css'
  - 'src/App/stylesheet/icons.scss'

linters:
  StringQuotes:
    enabled: true
    style: double_quotes
  Indentation:
    enabled: true
    width: 2
  ImportPath:
    enabled: true
    filename_extension: true
  SelectorFormat:
    enabled: true
    exclude: 'src/App/stylesheet/icons.scss'
    convention: hyphenated_BEM
  NestingDepth:
    enabled: true
    max_depth: 5
  SelectorDepth:
    enabled: true
    max_depth: 4
